language: php
sudo: false

php:
    - "7.2"
    - "7.3"
    - "7.4"

matrix:
    fast_finish: true

install:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit
    - vendor/bin/psalm
